### ISSUE TITLE
When a user select word(s) in a webpage, it will show the definition of the word

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#1]
# User scenario
The user wants to find the meaning of a word so he/she highlights it. 

# Expected Behavior of the Program
The program will show the meaning(s) of this word. 

# Todo
- [x] 1. Create a script that will detect the highlighted word(s) and then send it to the dictionary processing script.
- [x] 2. Create a script that will accept the word from the 1. and then query ~our service in 2 the dictionary service~ the selected dictionary API. 
- [x] 3. Create a ~page~ popup that displays the result of 2.

**Comment by chuaweijie** [comment]
There is a need to change the development direction due to [Cross-Origin Read Blocking](https://www.chromestatus.com/feature/5629709824032768). For further information, please refer to this [article in Wikipedia](https://en.wikipedia.org/wiki/Same-origin_policy). 

The plan now is to write a server service that serves as a proxy to make requests to our intended database services.

**Comment by chuaweijie** [comment]
Change of plans again. Due to how hard it is to write a service to extract the data from a dictionary site, I am going to change the direction of the development to get data from Google and [Oxford API](https://developer.oxforddictionaries.com/).

**Comment by chuaweijie** [comment]
The issue has been solved.
