### ISSUE TITLE
After a user searches for a word, it will be automatically added to his or her flashcard deck

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#3]
# User Scenario
The same as #1.

# Expected Behavior of the Program
It will save this word and its definition into the database. It will update its lookup count if it already exists

# Todo
- [x] 1. Find out the storage options available for a Chrome extension. Do we need a hosted DB?
- [x] 2. Design the ways the data are stored according to the storage option available to Chrome extension
- [x] ~3. Design test cases to test extreme use cases of this extension.~ 
~* How will the storage's speed be if we have 2,000,000 words stored with the extension?~
~* Respond time must not be more than 500ms during the above test.~ 
Simulated with [Browser database comparison](https://nolanlawson.github.io/database-comparison/)
- [x] 4. Code the storage
- [x] 5. Program the word saving logic.

**Comment by chuaweijie** [comment]
[IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB) seems to be the way to go if I were to publish this extension.

**Comment by chuaweijie** [comment]
The coding logic has been committed with d69a807. My apologies that I forgot to make a branch.
