### ISSUE TITLE
As a user, I would like to be able to view all the words and its status in my flash card.

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#4]
# User Scenario(s)
1. User is wondering how many words he or she has amassed. 
2. The user wants to find out how many repeated searches he/she has done with a word. 
3. The user just wants a top-down view of his/her list of words. 

# Expected Behavior of the Program
1. It will show a list of words sorted with the newest searched word on top. 
2. Users can sort the list ascendingly or descendingly according to newest, mastery, and number of searches.
3. It will have a UI element that shows how many times this word has been searched
4. It will have a UI element show the status of the word. (New, Level 1, Level 2, Level 3, Mastered)
5. Selecting the word will show the definition to the user and enable the user to mark it as mastered or delete the word. 
- The rationale for this is because there might be instances where users accidentally triggered a search. 
- I believe that users know their own mastery better than our algorithms so we need to give control to the user. 
6. Users can search the vocabulary. 
7. Users can filter the words according to the status of the word. 

# Todo
- [x] 1. A listing page with tiles of words. 
- [x] 2. Each word tile. They will have the status of the word, how many time it has been searched. 
- [ ] ~3. Sorting function on the listing page~
- [x] 4. Searching function on the listing page. It has to have a live search and filter function. 
- [x] 5. Function to mark word as deleted
- [x] 6. Function to mark work as mastered
- [x] 7. Word status filtering function. 
- [x] 8. UI to show the definition of the word.

**Comment by chuaweijie** [comment]
I've removed the sorting function from this requirement because I deem that to be redundant.
