### ISSUE TITLE
As a user, I would like to be able to set Flashcard Dictionary to my liking

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#5]
# User Scenario
A user wants to set something or configure something to their liking. 

# Expected Behavior of the Program
1. A user is able to toggle if selecting the word will perform a search or not. The alternative behaviour is to search from the context menu. 
2. A user is able to set the maximum number of words that are being tested in their quiz
3. A user is able to set when the extension will remind them to take their daily quiz. 

# Todo
- [ ] 1. Write a page with all the setting controls. 
- [ ] 2. Find a storing mechanism for these settings.
- [ ] 3. Write the logic to read and write settings into storage. 
- [ ] 4. The logic to change the extension's behaviour when the setting is different.
