### ISSUE TITLE
As a user, I would like to get notification when it is time for me to review my vocabularies

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#6]
# User Scenario
The user is using Chrome normally. The extension prompts the user to practice his / her vocabulary. 

# Expected Behavior of the Program
1. The program will prompt the user at the correct pre-defined time regardless of the user's current time zone. 
2. The prompt will have three buttons. 
* Start
* Snooze for 10 minutes
* Cancel
3. The notification will log these data for future uses. 

# Todo
- [ ] 1. Create a logic to check the time defined in #5 
- [ ] 2. Launch the notification when the time is there. 
- [ ] 3. Write the snooze logic
- [ ] 4. Write the logic to start and cancel.
- [ ] 5. Write the logic to store start, snooze and cancel.
