### ISSUE TITLE
As a user, I would like to be able to have a quiz about the vocabulary I have

### ISSUE THREAD

**Issue by chuaweijie** [chuaweijie/Flashcard-Dictionary#7]
# User Scenario
1. A user launched the quiz mode of flashcard dictionary manually.
2. A user launched the quiz mode of flashcard dictionary from a notification. 

# Expected Behavior of the Program
1. The system will test the up to the maximum number of words ~defined in #5~ hardcoded to 15. 
* The program will display the word that is due today or overdue. 
* It will choose based on which word is the closest to mastery then it will choose the word that is the longest from its due date. 
2. The user will go through the test, there will be two outcomes. 
* The user gets it correct and it will be moved to a higher level until it is in mastery. 
* The user gets it wrong and it will be moved to a lower level. 
3. Once the user has finished the quiz, it will display that day's performance report. 

# Todo
- [x] 1. Code the quiz system logic with the ~maximum~ number setting based on #5. The default~ number will be 15. 
- [x] 2. Code the logic of pulling the words into the quiz. 
* The program will display the word that is due today and before. 
* It will choose based on which word is the closest to mastery then it will choose the words after that.
- [x] 3. Code the system logic of moving the word to different "level" ~and set the next test date~. 
- [x] 4. Code the performance report

**Comment by chuaweijie** [comment]
New - 1 day.
Level 1 - 3 days
Lever 2 - 1 week 
Level 3 - 2 weeks
Mastered - 1 month
